name: Build and deploy Node.js app to Azure Web App - madhav-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # use ubuntu, faster & lighter than windows for Node.js
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # You don’t need build/test unless you actually have them in package.json
      - name: Run tests (if any)
        run: npm run test --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # required for requesting the JWT
      contents: read    # required for checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3157A94DF1FF434EB0FD9CF04275BC1D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DA22ABE82B849DC815262D3AA851077 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8275B3C9ACFB41F89C3D361B39C5BDB0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'madhav-backend'
          slot-name: 'Production'
          package: .
